// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHEXSvOStLlhZJzQSHDVpUaiF_BQEJn6g',
    appId: '1:25462617153:web:9a47e0d09ee41507b8c2c0',
    messagingSenderId: '25462617153',
    projectId: 'weather-now-9a8c7',
    authDomain: 'weather-now-9a8c7.firebaseapp.com',
    storageBucket: 'weather-now-9a8c7.firebasestorage.app',
    measurementId: 'G-RDC1DJEVQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGyQnQzCdQVURPyxR15wffiA_wXRID8MI',
    appId: '1:25462617153:android:7ec206d04e80d16db8c2c0',
    messagingSenderId: '25462617153',
    projectId: 'weather-now-9a8c7',
    storageBucket: 'weather-now-9a8c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK9i6lELtV1zPmgge_kPRulljtBSQgBh0',
    appId: '1:25462617153:ios:8b63a1feadd7298db8c2c0',
    messagingSenderId: '25462617153',
    projectId: 'weather-now-9a8c7',
    storageBucket: 'weather-now-9a8c7.firebasestorage.app',
    iosBundleId: 'com.example.weatherNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK9i6lELtV1zPmgge_kPRulljtBSQgBh0',
    appId: '1:25462617153:ios:8b63a1feadd7298db8c2c0',
    messagingSenderId: '25462617153',
    projectId: 'weather-now-9a8c7',
    storageBucket: 'weather-now-9a8c7.firebasestorage.app',
    iosBundleId: 'com.example.weatherNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHEXSvOStLlhZJzQSHDVpUaiF_BQEJn6g',
    appId: '1:25462617153:web:ff446ca55c00f4abb8c2c0',
    messagingSenderId: '25462617153',
    projectId: 'weather-now-9a8c7',
    authDomain: 'weather-now-9a8c7.firebaseapp.com',
    storageBucket: 'weather-now-9a8c7.firebasestorage.app',
    measurementId: 'G-57VL68RPMD',
  );
}
